spring:
  application:
    name: tieba
  datasource:
    url: jdbc:mysql://localhost:3306/tieba?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
app:
  jwt:
    secret: TieBaSecretKey2026VeryLongSecretKeyForJWTSigningPurposes!
    expiration-ms: 2592000000
langchain4j:
  open-ai:
    api-key: ${DEEPSEEK_KEY:sk-f49d4e495ddb409d9f010ca4a142ccc6}
    base-url: https://api.deepseek.com/v1
    model-name: deepseek-v4-flash
    max-tokens: 1024
    temperature: 1.2

server:
  port: 4000
logging:
  level:
    org.springframework.boot.autoconfigure.jdbc: DEBUG
    org.mybatis: DEBUG
    com.zaxxer.hikari: DEBUG
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/*.xml